spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://47.101.175.31:3306/jingxi?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  redis:
    host: 47.101.175.31
    port: 6379
    timeout: 10
    password: 123456
    jedis:
      pool:
        max-active: 1000
        max-idle: 500
        #5秒
        max-wait: 5
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081