eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    # 表示是否注册自身到eureka服务器
    register-with-eureka: false
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka
#server:
#  port: 8761
management:
  context-path: /